name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.10"] # test de 2 version de python en parallele

    steps:
      - uses: actions/checkout@v5

      - name: Show branch informations and OS
        run: |
          echo "Nom branche: ${{ github.ref }}"
          echo "OS du runner: ${{ runner.os }}"

      - name: Set up Python for Demo
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show used version of python
        run: python --version

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest TP1/test.py
